# Generated by Django 3.1.2 on 2020-10-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('K', 'Kruche'), ('D', 'Drożdżowe'), ('S', 'Serniki')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'secondary'), ('D', 'danger'), ('P', 'primary')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
