# Generated by Django 3.1.2 on 2020-11-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201108_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='static/images/products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('K', 'Kruche'), ('S', 'Serniki'), ('D', 'Drożdżowe')], max_length=1),
        ),
    ]
