# Generated by Django 3.1.2 on 2020-11-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20201112_1947'),
        ('core', '0044_auto_20201112_1948'),
    ]

    operations = [
    ]
