# Generated by Django 3.0.7 on 2021-01-26 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20210126_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Cake', 'verbose_name_plural': 'Cakes'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Ordered cake', 'verbose_name_plural': 'Ordered cakes'},
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'secondary'), ('P', 'primary'), ('D', 'danger')], max_length=1, null=True),
        ),
    ]
