# Generated by Django 3.0.7 on 2021-01-29 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20210127_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allergens',
            field=models.CharField(default='brak', max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='calories',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'secondary'), ('D', 'danger'), ('P', 'primary')], max_length=1, null=True),
        ),
    ]
